--vfibubuchungiazi MIS-Schnittstelle

CREATE OR REPLACE VIEW VFIBUBUCHUNGIAZI (FIBUNR, JAHR, MONAT, KONTONR, KONTOBEZEICHNUNG, BETRAG) AS 
SELECT F.FIBUNR, FK.JAHR, DATEFORMAT(FB.BUCHDAT,'Mm') MONAT,  FK.KTO KONTONR, FK.KONTOBEZ1 KONTOBEZEICHNUNG,
TRIM(STR(SUM(CASE WHEN FB.SOLL = 'Y' THEN FB.BETRAG ELSE -FB.BETRAG END), 13,2))  BETRAG
FROM FIBU F 
JOIN FIBUKONTO1 FK ON FK.FIBUNR = F.FIBUNR
JOIN FIBUBUCHUNG FB ON FB.FIBUNR = FK.FIBUNR AND FB.JAHR = FK.JAHR AND FB.KTO = FK.KTO
GROUP BY F.FIBUNR, FK.JAHR, DATEFORMAT(FB.BUCHDAT,'Mm'), FK.KTO, FK.KONTOBEZ1
ORDER BY F.FIBUNR, FK.JAHR, DATEFORMAT(FB.BUCHDAT,'Mm'), FK.KTO